# Generated by Django 5.1.2 on 2024-11-15 08:40

import django.db.models.deletion
import user_preference.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('min_height', models.PositiveIntegerField(blank=True, null=True)),
                ('max_height', models.PositiveIntegerField(blank=True, null=True)),
                ('min_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('max_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('min_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[user_preference.models.positive_decimal])),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[user_preference.models.positive_decimal])),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_education', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_religion', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
