# Generated by Django 5.1.2 on 2024-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subscription', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
