# Generated by Django 5.1.2 on 2024-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('marital_status', 'Marital Status'), ('language', 'Language'), ('education', 'Education'), ('religion', 'Religion'), ('caste', 'Caste'), ('location', 'Location'), ('profession', 'Profession')], max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
