# Generated by Django 5.1.2 on 2024-11-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_generaltable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
