# Generated by Django 5.1.2 on 2024-11-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_address_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='D:\\DJANGO_Project\\Matrimonial_sw\\user_icon.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
