# Generated by Django 5.1.2 on 2024-11-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
