# Generated by Django 5.1.2 on 2024-11-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_subscription'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, default='S01', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.subscription'),
        ),
    ]
